#!/bin/bash

input_file=$1
output_file=${input_file:0:-4}.mkv
printf "%s\n%s\n\n" "Current input file is: $input_file" "The output file will be: $output_file"

printf "%s\n" "Choose an action..." &&
select opt in analyze convert ; do    
    if [[ $opt == "analyze" ]] ; then
        ffmpeg -analyzeduration 100M -probesize 100M -i "$input_file"
    elif [[ $opt == "convert" ]] ; then
        ffmpeg \
            -analyzeduration 100M -probesize 100M \
            -i "$input_file" \
            -map 0:1 -map 0:3 -map 0:4 -map 0:5 -map 0:6 \
            -metadata:s:a:0 language=ita -metadata:s:a:0 title="Italian stereo" \
            -metadata:s:a:1 language=eng -metadata:s:a:1 title="English stereo" \
            -metadata:s:s:0 language=ita -metadata:s:s:0 title="Italian" \
            -metadata:s:s:1 language=eng -metadata:s:s:1 title="English" \
            -codec:v libx264 -crf 21 \
            -codec:a libmp3lame -qscale:a 2 \
            -codec:s copy \
        output.mkv
    else
        echo hej;
    fi
done 

#printf "%s\n" "Disconnecting from all connections..." &&
#if [[ "$(read -e -p '[y/N]? > '; echo $REPLY)" == [Yy]* ]] ; then
#    sudo netctl stop-all && printf "\n" && showNetworkStatus
#else
#    printf "\n"
#fi
